### ISSUE TITLE
Thank You, Vy!

### ISSUE THREAD

**Issue by slammajamma28** [Vyrastas/bbcode_guide_template#13]
PST upgraded the entire site in the last 24 hours. Since the site upgraded, this generator broke. But the way guides are now going to be created is being updated as well. This template generator will be obsolete when the features finish rolling out.

You're more than welcome to fix it to scrape the site now, but I thought I'd save you the trouble by letting you know it won't be necessary soon.

And, of course, I wanted to say thank you for hosting and fixing this invaluable page over the last 7 years.

**Comment by Vyrastas** [comment]
Hey no problem, glad to see the mythical site update actually happen.

And good to hear that there'll be an alternative to the template, because honestly I wasn't going to host it any further if it completely broke like this.  😄 

I'll remove the actual template from my site and add a placeholder page to inform everyone that the template is gone forever.  If there's a link/page on the site you want me to add to the placeholder page where people can be redirected for info, let me know.

Eventually I'll just remove this repo altogether.

**Comment by slammajamma28** [comment]
That should work! Something like

"With the new upgrade to PST/XBA, this template generator is no longer needed. Keep an eye on Guide Central (https://www.playstationtrophies.org/forum/forum/3207-guide-central/) for info on how to use the new guide system when it is available."

Thanks again Vy, you legend!

**Comment by Vyrastas** [comment]
Done!

http://vyrastas.com/guide_template.htm
